import '@/src/styles/globals.css'

import { Poppins } from 'next/font/google'

import MainNavbar from '@/src/components/MainNavbar'

import { Providers } from './providers'

const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Smith Cabin',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  // const session = await getServerSession(authOptions)

  return (
    <html lang="en" className={poppins.className}>
      <body className='h-[100vh] w-[100vw]'>
        <Providers>
          <MainNavbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
