import './globals.css'

import { Inter } from 'next/font/google'

import MainNavbar from './components/Navbar'
import { Providers } from './providers'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Smith Cabin',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Providers>
          <MainNavbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
