import '@/src/styles/globals.css'
import 'react-toastify/dist/ReactToastify.css'

import { Poppins } from 'next/font/google'
import { ToastContainer } from 'react-toastify'

import MainNavbar from '@/src/components/MainNavbar'

import { Providers } from '../components/providers'

const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'LM Cabin',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={poppins.className}>
      <body className="w-full h-screen">
        <Providers>
          <MainNavbar />
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  )
}
